version: '3'

networks:
  web:

services:
  chrome:
    image: selenium/standalone-chrome:latest
    hostname: chrome
    networks:
      - web
    ports:
      - "5900:5900"
      - "4444:4444"
    privileged: true
    shm_size: 2g

  qipu:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - web
    depends_on:
      - chrome
    stdin_open: true
    tty: true